name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.8
  # flutter_vision: ^1.1.4
  # camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase: ^9.0.3
  firebase_core: ^3.6.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - assets/logo1.png
    - assets/coffee_logo.png
    - assets/gallery_icon.png
    - assets/home_icon.png
    - assets/profile_icon.png

